
/*******************************************************
** AUTOMATICALLY CREATED MOBILE LOADING CONFIGURATION **
*******************************************************/

// Please, do not edit this file. It is automatically generated by 'build.mutua.ts' task on every build with information present in 'mutua.instance-project.config.ts' and 'mutua.available.modules.and.components.config.ts'

// Included by 'nativescript/.../components.modules.ts' to load the needed components and modules and make them available to the application

// components
/////////////

import { AppComponent } from '../../components/app.component';
import { MPHomeComponent } from '../../components/pages/mp-home/mp-home.component';
import { MPCadastraITComponent } from '../../components/pages/mp-cadastra-it/mp-cadastra-it.component';
import { MPListaITsComponent } from '../../components/pages/mp-lista-its/mp-lista-its.component';
import { MPLoginComponent } from '../../components/pages/mp-login/mp-login.component';

export const MutuaExportedComponents: any[] = [AppComponent,MPHomeComponent,MPCadastraITComponent,MPListaITsComponent,MPLoginComponent];

// routes
/////////

import { MPHomeRoutes } from '../../components/pages/mp-home/mp-home.routes';
import { MPCadastraITRoutes } from '../../components/pages/mp-cadastra-it/mp-cadastra-it.routes';
import { MPListaITsRoutes } from '../../components/pages/mp-lista-its/mp-lista-its.routes';
import { MPLoginRoutes } from '../../components/pages/mp-login/mp-login.routes';

export const MutuaExportedRoutes: any[] = [...MPHomeRoutes,...MPCadastraITRoutes,...MPListaITsRoutes,...MPLoginRoutes];

// modules
//////////


export const MutuaExportedModules: any[] = [];

export const MutuaAppComponent: any = AppComponent;
